version: '3'
services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../../:/var/www/public
      - ../config:/etc/nginx/conf.d/
      - ../logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../../:/var/www/public
